version: '3.9'

services:

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER:-adminuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-DevOps123!}
      POSTGRES_DB: ${DB_NAME:-usuarios_db}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: spring_app
    depends_on:
      - db
    ports:
      - "${SPRING_PORT:-8080}:8080"
    environment:
      # Base de datos
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"

      # JWT
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}

      # SMTP para notificaciones por correo
      SMTP_HOST: ${SMTP_HOST:-localhost}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USERNAME: ${SMTP_USERNAME:-}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-}
      SMTP_AUTH: ${SMTP_AUTH:-true}
      SMTP_STARTTLS_ENABLE: ${SMTP_STARTTLS_ENABLE:-true}
      SMTP_STARTTLS_REQUIRED: ${SMTP_STARTTLS_REQUIRED:-true}
      SMTP_FROM: ${SMTP_FROM:-noreply@eventos.local}
    restart: always

volumes:
  pgdata: